# Generated by Django 4.2.5 on 2023-10-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseID',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
